#!/bin/sh
# A very basic IPtables / Netfilter script

PATH='/sbin'

# Flush the tables to apply changes
iptables -F

# Default policy to drop 'everything' but our output to internet

iptables -P FORWARD DROP
iptables -P INPUT   DROP
iptables -P OUTPUT  ACCEPT

# Allow established connections (the responses to our outgoing traffic)
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

# Allow local programs that use loopback (Unix sockets)
iptables -A INPUT -s 127.0.0.0/8 -d 127.0.0.0/8 -i lo -j ACCEPT

## Portforwards ###

# iptables -A INPUT -p tcp --dport 9200 -m state --state NEW -j ACCEPT
# incoming SSH/SCP conections to this machine,
iptables -A INPUT -p tcp --dport 22 -m state --state NEW -j ACCEPT
#mail
iptables -A OUTPUT -p tcp --dport 587  -j ACCEPT
#webb
# iptables -A INPUT -p tcp --dport 443 -m state --state NEW -j ACCEPT
iptables -A INPUT -p tcp --dport 80 -m state --state NEW -j ACCEPT

# Nagios
iptables -A INPUT -p tcp --dport 5666 -m state --state NEW -j ACCEPT
# Allow ping from Nagios server
iptables -A INPUT -s monitor.orestad-linux.se -p ICMP --icmp-type 8 -j ACCEPT
